# Generated by Django 5.1.1 on 2024-09-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_user_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_crm',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='doctor_especialidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_genero',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_telefone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
