# Generated by Django 5.1.1 on 2024-10-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='especialidade_medico',
            field=models.CharField(default='Indefinido', max_length=100),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nome_medico',
            field=models.CharField(default='Indefinido', max_length=100),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nome_paciente',
            field=models.CharField(default='Indefinido', max_length=100),
        ),
    ]
